### ISSUE TITLE
Feature Request for Sample:  Service Endpoint 

### ISSUE THREAD

**Issue by jonathan305** [Microsoft/azure-devops-dotnet-samples#132]
I would like a client sample for Getting list of Service Endpoint and Creating a Service Endpoint.
Any idea how long this will take, in meantime I can access the API directly...

https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/endpoints/get%20service%20endpoints?view=vsts-rest-5.0

https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/endpoints/create?view=vsts-rest-5.0

Thank you,

Jonathan

**Comment by jonathan305** [comment]
I have successfully retrieved list of Service Endpoint directly consuming the API.  so this is low priority for me.  If anyone wants the code please advise.  luriejonathan70@gmail.com

**Comment by jonathan305** [comment]
I'd like to generate the Request Body for the POST Service:  https://{accountName}.visualstudio.com/{project}/_apis/serviceendpoint/endpoints?api-version=5.0-preview.2 

Does VstsApi support Swagger so I can autogenerate the Request Body class?

**Comment by BiribiriJaNai** [comment]
I'm in the same position here. I'm trying to gradually move from pure REST API calls to client librairies but ConnectedServiceHttpClient class is lacking in documentation, samples and still does not provide a method for endpoint deletion.

**Comment by boblechat** [comment]
Is there anyone looking at this?
If I remember correctly, there used to be a `ServiceEndpointHttpClient` class in an older version of the client libraries.
How comes it is no longer available?

**Comment by willsmythe** [comment]
`ServiceEndpointHttpClient` lives in https://www.nuget.org/packages/Microsoft.VisualStudio.Services.ServiceEndpoints.WebApi

The REST API reference docs (https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints?view=azure-devops-rest-5.1) has some good examples that show how to interact with the APIs in general. These examples can be translated to the .NET client library (which uses the same models/contracts as the REST APIs).

Also see the linked PR which adds a few .NET/C# samples.

**Comment by willsmythe** [comment]
See [ClientLibrary/Samples/Serviceendpoint/EndpointsSample.cs](https://github.com/Microsoft/azure-devops-dotnet-samples/blob/master/ClientLibrary/Samples/Serviceendpoint/EndpointsSample.cs)
