### ISSUE TITLE
Create Work Item as Specific User

### ISSUE THREAD

**Issue by tomaustin700** [Microsoft/azure-devops-dotnet-samples#223]
Hi,

How can I create a work item as a specific user? Is this even possible? Currently I am passing VssCredentials into VssConection and this will create the work items as the user that I have passed into VssCredentials however in some circumstances I need to create work items as other users. When creating the work item I have tried setting System.CreateUser in the patch document however this doesn't seem to change anything.

Thanks

**Comment by nschonni** [comment]
This is a little dated http://blogs.microsoft.co.il/shair/2010/08/23/tfs-api-part-29-tfs-impersonation/ but you need the "Make requests on behalf of others" permission. Usually this is restricted to service accounts.

**Comment by tomaustin700** [comment]
@nschonni This does not seem to be possible anymore as TeamFoundationIdentity does not exist anymore when using version 16.143.0 of Microsoft.TeamFoundationServer.Client in a .net core project.

**Comment by danhellem** [comment]
Have you tried to setting the createdby field = <your identity> using the bypass rules?

**Comment by tomaustin700** [comment]
@danhellem Thanks, that works!
