### ISSUE TITLE
VssConnection behind firewall / proxy

### ISSUE THREAD

**Issue by BiribiriJaNai** [microsoft/azure-devops-dotnet-samples#230]
Is it possible to have an example on how to use a `VssConnection` object behind a proxy?
Considering this sample (.NET Core 2.1.X):
```csharp
VssCredentials credentials = new VssBasicCredential("", "<pat>");
VssConnection connection = new VssConnection(new Uri("https://dev.azure.com/<organization>"), credentials);
ProjectHttpClient client = connection.GetClient<ProjectHttpClient>();
var project = await client.GetProject("<project>");
```

works fine anywhere except behind a (corporate) proxy where I get the following error:

![image](https://user-images.githubusercontent.com/29836717/54429301-6b864d00-4720-11e9-9ec7-cbb58f31e879.png)

I tried to play with `WebRequest.Proxy` and `VssHttpMessageHandler.DefaultWebProxy` without any success. The lack of documentation on these libraries is a serious pain the neck!

**Comment by BiribiriJaNai** [comment]
Anyone? Thanks.

**Comment by mjwoodsphx** [comment]
The easiest way to have these libraries use a web proxy is to add this sections to your web/app config file in the configuration section:


<system.net>
      <settings>
        <ipv6 enabled="true"/>
      </settings>
      </settings>
	<defaultProxy useDefaultCredentials="true" enabled="true">
        <proxy bypassonlocal="true" proxyaddress="[Your proxy URL]:[Port]" />
    </defaultProxy>
</system.net>

**Comment by subbu152** [comment]
Below code should resolve your issue.

VssHttpMessageHandler.DefaultWebProxy = new WebProxy(new Uri("[Your proxy URL]:[Port]"), true, new string[] { "[Your Devops URL]" }, CredentialCache.DefaultCredentials);
var handler = new VssHttpMessageHandler(new VssBasicCredential(string.Empty, config[Constants.VstsPat]),
new VssClientHttpRequestSettings() { BypassProxyOnLocal = true, SuppressFedAuthRedirects = true, AllowAutoRedirect = true }
);
var connection = new VssConnection(accountUri, handler, null);

**Comment by BiribiriJaNai** [comment]
@mjwoodsphx, thanks for the suggestion but the XML "app.config" approach didn't work in a .NET Core console app.
@subbu152, I was missing the `VssClientHttpRequestSettings` part when I played with `VssHttpMessageHandler.DefaultWebProxy`. It now works like a charm. Thanks a lot!

**Comment by subbu152** [comment]
> @mjwoodsphx, thanks for the suggestion but the XML "app.config" approach didn't work in a .NET Core console app.
> @subbu152, I was missing the `VssClientHttpRequestSettings` part when I played with `VssHttpMessageHandler.DefaultWebProxy`. It now works like a charm. Thanks a lot!

You are welcome. Glad to know it worked for you. 👍

**Comment by montapas** [comment]
@subbu152 i am trying to connect using https://proxy.server.com:8989 and i am getting https scheme does not supported by .net. if i use http: then also it is not working can you help me on this. I am using .net framework

Please help
