### ISSUE TITLE
How to apply inherited process to existing team project?

### ISSUE THREAD

**Issue by subodhsohoni** [microsoft/azure-devops-dotnet-samples#263]
@willsmythe , Please add a sample to apply the customized inherited process to an existing project.

**Comment by danhellem** [comment]
not sure i understand, are you trying to change the process of an existing project? Or do you have a project using hosted xml and you are trying to change it to inherited? or are you on-prem?

**Comment by subodhsohoni** [comment]
@danhellem, 
I have a project that uses Scrum process on Azure DevOps (not on-prem). I have created an inherited scrum process in a program. It is working as desired when applied through UI to a project. I want to apply it to an existing project that is using Scrum process, using APIs. I haven’t been able to get any code for that nor have been successful in creating that. Can you please send me a snippet of that only?

With best regards,
Subodh Sohoni

**Comment by danhellem** [comment]
so you just need an example to change the project from using scrum to scrum - inherited?

**Comment by subodhsohoni** [comment]
Yes

**Comment by danhellem** [comment]
Actually i don't see a way of doing that from the REST API docs...let me check with the team. Stand by

**Comment by danhellem** [comment]
Sorry, i confirmed that we don't allow this via REST APIs. No plans to make the API public :(
