### ISSUE TITLE
Clarify whether connection and client(s) need to be disposed

### ISSUE THREAD

**Issue by milesizzo** [microsoft/azure-devops-dotnet-samples#266]
Hi,

All of the sample code I've seen for using `VssConnection` and the various clients don't dispose the objects.

1. Should I dispose of a client after using it? For example:
```
using (var client = connection.GetClient<BuildHttpClient>())
{
    // use client
}
```
2. Should I dispose of a connection after I've finished using it?
3. Should I construct a `VssConnection` each time I need a client, or can I construct multiple clients from a single connection?

**Comment by danhellem** [comment]
you can create multiple clients from one connection. Although the samples don't show it, it is a good idea to clean up the connection once you are done using it

**Comment by milesizzo** [comment]
Should I be disposing of the HTTP client(s) that I get from the connection? It seems when I do that the subsequent clients are unusable (which perhaps answers my own question).
