### ISSUE TITLE
Need sample/help for QueueBuildAsync

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/azure-devops-dotnet-samples#297]
I cannot figure out how to queue a build, specifically a YAML pipeline. I always get the error message:

> Could not queue the build because there were validation errors or warnings.

There is no further information.

Here's my code:

```csharp
string collectionUri = $"https://dev.azure.com/{organization}";
var creds = new VssBasicCredential(string.Empty, pat);
var connection = new VssConnection(new Uri(collectionUri), creds);

var projectClient = connection.GetClient<ProjectHttpClient>();
var project = await projectClient.GetProject(projectName);

var buildClient = await connection.GetClientAsync<BuildHttpClient>();
var definition = await buildClient.GetDefinitionAsync(projectName, 1253);

var build = new Build
{
    Definition = definition,
    Project = project,
};

var response = await buildClient.QueueBuildAsync(build, ignoreWarnings: true);
```

Setup:
- I have full admin access in the organization
- I created a PAT will full access
- Microsoft.TeamFoundationServer.Client - v16.153.0
- .NET Core 3.1
- In debug, `definition` and `project` are what I would expect them to be
- The pipeline is just the starter pipeline, so no variables or parameters are used

![image](https://user-images.githubusercontent.com/1784452/96045212-43e4f280-0e37-11eb-9f56-f09c1040a329.png)

What am I doing wrong?

**Comment by MisinformedDNA** [comment]
Sign... the pipeline was only defined on a specific branch. Once I set the branch name, it worked fine.

However, now I'm stuck at trying to set a variable for the build. How can I do that?

**Comment by icnocop** [comment]
@MisinformedDNA  I found this code snippet https://stackoverflow.com/a/52777688/90287

**Comment by MisinformedDNA** [comment]
Thanks. This is all I ended up needing:

```
var json = new JObject(new JProperty("pullRequestId", pullRequestId));
build.Parameters = JsonConvert.SerializeObject(json);
```
